//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRX_KAVA_API.WebSrvWCS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebSrvWCS.WCS_forWMSSoap")]
    public interface WCS_forWMSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MoveTask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TRX_KAVA_API.WebSrvWCS.WCS_Ask_Result MoveTask(string from, string to, string Task_number, string barcode, string out_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MoveTask", ReplyAction="*")]
        System.Threading.Tasks.Task<TRX_KAVA_API.WebSrvWCS.WCS_Ask_Result> MoveTaskAsync(string from, string to, string Task_number, string barcode, string out_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OutTask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TRX_KAVA_API.WebSrvWCS.WCS_Ask_Result OutTask(string from, string to, string Task_number, string barcode, string res);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OutTask", ReplyAction="*")]
        System.Threading.Tasks.Task<TRX_KAVA_API.WebSrvWCS.WCS_Ask_Result> OutTaskAsync(string from, string to, string Task_number, string barcode, string res);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InTask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TRX_KAVA_API.WebSrvWCS.WCS_Ask_Result InTask(string from, string to, string Task_number, string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InTask", ReplyAction="*")]
        System.Threading.Tasks.Task<TRX_KAVA_API.WebSrvWCS.WCS_Ask_Result> InTaskAsync(string from, string to, string Task_number, string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContainerOutConveyorAskToNewPort", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TRX_KAVA_API.WebSrvWCS.WCS_Ask_Result ContainerOutConveyorAskToNewPort(string from, string to, string Task_number, string barcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContainerOutConveyorAskToNewPort", ReplyAction="*")]
        System.Threading.Tasks.Task<TRX_KAVA_API.WebSrvWCS.WCS_Ask_Result> ContainerOutConveyorAskToNewPortAsync(string from, string to, string Task_number, string barcode);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WCS_Ask_Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        private string error_codeField;
        
        private string error_messageField;
        
        private string ask_numField;
        
        private string place_instockField;
        
        private string sorting_portField;
        
        private bool pallet_wrappingField;
        
        private string task_numField;
        
        private string reserve_field1Field;
        
        private string reserve_field2Field;
        
        private string reserve_field3Field;
        
        private string reserve_field4Field;
        
        private string reserve_field5Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string error_code {
            get {
                return this.error_codeField;
            }
            set {
                this.error_codeField = value;
                this.RaisePropertyChanged("error_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string error_message {
            get {
                return this.error_messageField;
            }
            set {
                this.error_messageField = value;
                this.RaisePropertyChanged("error_message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ask_num {
            get {
                return this.ask_numField;
            }
            set {
                this.ask_numField = value;
                this.RaisePropertyChanged("ask_num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string place_instock {
            get {
                return this.place_instockField;
            }
            set {
                this.place_instockField = value;
                this.RaisePropertyChanged("place_instock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sorting_port {
            get {
                return this.sorting_portField;
            }
            set {
                this.sorting_portField = value;
                this.RaisePropertyChanged("sorting_port");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool pallet_wrapping {
            get {
                return this.pallet_wrappingField;
            }
            set {
                this.pallet_wrappingField = value;
                this.RaisePropertyChanged("pallet_wrapping");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string task_num {
            get {
                return this.task_numField;
            }
            set {
                this.task_numField = value;
                this.RaisePropertyChanged("task_num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string reserve_field1 {
            get {
                return this.reserve_field1Field;
            }
            set {
                this.reserve_field1Field = value;
                this.RaisePropertyChanged("reserve_field1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string reserve_field2 {
            get {
                return this.reserve_field2Field;
            }
            set {
                this.reserve_field2Field = value;
                this.RaisePropertyChanged("reserve_field2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string reserve_field3 {
            get {
                return this.reserve_field3Field;
            }
            set {
                this.reserve_field3Field = value;
                this.RaisePropertyChanged("reserve_field3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string reserve_field4 {
            get {
                return this.reserve_field4Field;
            }
            set {
                this.reserve_field4Field = value;
                this.RaisePropertyChanged("reserve_field4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string reserve_field5 {
            get {
                return this.reserve_field5Field;
            }
            set {
                this.reserve_field5Field = value;
                this.RaisePropertyChanged("reserve_field5");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WCS_forWMSSoapChannel : TRX_KAVA_API.WebSrvWCS.WCS_forWMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCS_forWMSSoapClient : System.ServiceModel.ClientBase<TRX_KAVA_API.WebSrvWCS.WCS_forWMSSoap>, TRX_KAVA_API.WebSrvWCS.WCS_forWMSSoap {
        
        public WCS_forWMSSoapClient() {
        }
        
        public WCS_forWMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCS_forWMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCS_forWMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCS_forWMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TRX_KAVA_API.WebSrvWCS.WCS_Ask_Result MoveTask(string from, string to, string Task_number, string barcode, string out_number) {
            return base.Channel.MoveTask(from, to, Task_number, barcode, out_number);
        }
        
        public System.Threading.Tasks.Task<TRX_KAVA_API.WebSrvWCS.WCS_Ask_Result> MoveTaskAsync(string from, string to, string Task_number, string barcode, string out_number) {
            return base.Channel.MoveTaskAsync(from, to, Task_number, barcode, out_number);
        }
        
        public TRX_KAVA_API.WebSrvWCS.WCS_Ask_Result OutTask(string from, string to, string Task_number, string barcode, string res) {
            return base.Channel.OutTask(from, to, Task_number, barcode, res);
        }
        
        public System.Threading.Tasks.Task<TRX_KAVA_API.WebSrvWCS.WCS_Ask_Result> OutTaskAsync(string from, string to, string Task_number, string barcode, string res) {
            return base.Channel.OutTaskAsync(from, to, Task_number, barcode, res);
        }
        
        public TRX_KAVA_API.WebSrvWCS.WCS_Ask_Result InTask(string from, string to, string Task_number, string barcode) {
            return base.Channel.InTask(from, to, Task_number, barcode);
        }
        
        public System.Threading.Tasks.Task<TRX_KAVA_API.WebSrvWCS.WCS_Ask_Result> InTaskAsync(string from, string to, string Task_number, string barcode) {
            return base.Channel.InTaskAsync(from, to, Task_number, barcode);
        }
        
        public TRX_KAVA_API.WebSrvWCS.WCS_Ask_Result ContainerOutConveyorAskToNewPort(string from, string to, string Task_number, string barcode) {
            return base.Channel.ContainerOutConveyorAskToNewPort(from, to, Task_number, barcode);
        }
        
        public System.Threading.Tasks.Task<TRX_KAVA_API.WebSrvWCS.WCS_Ask_Result> ContainerOutConveyorAskToNewPortAsync(string from, string to, string Task_number, string barcode) {
            return base.Channel.ContainerOutConveyorAskToNewPortAsync(from, to, Task_number, barcode);
        }
    }
}
